#include "GameOpcodes.h"

namespace GameOpcode
{
    std::string_view ToString(uint32_t code)
    {
        switch (code)
        {
        case CG_ENTER:
            return "CG_ENTER";
        case CG_PLAY_START:
            return "CG_PLAY_START";
        case CG_EXIT:
            return "CG_EXIT";
        case CG_ITEM_PICKUP:
            return "CG_ITEM_PICKUP";
        case CG_ITEM_DROP:
            return "CG_ITEM_DROP";
        case CG_ITEM_MOVE:
            return "CG_ITEM_MOVE";
        case CG_QUEST_RESULT:
            return "CG_QUEST_RESULT";
        case CG_ITEM_TRADE_BUY:
            return "CG_ITEM_TRADE_BUY";
        case CG_ITEM_TRADE_SELL:
            return "CG_ITEM_TRADE_SELL";
        case CG_LEVEL_UP_CHECK:
            return "CG_LEVEL_UP_CHECK";
        case CG_CHAR_STATUS_UP:
            return "CG_CHAR_STATUS_UP";
        case GC_CHAR_SKILL_UP_EX:
            return "GC_CHAR_SKILL_UP_EX";
        case CG_ITEM_CONFIRM_NPC_REQUEST:
            return "CG_ITEM_CONFIRM_NPC_REQUEST";
        case CG_STORE_OPEN:
            return "CG_STORE_OPEN";
        case CG_STORE_PW_MODIFY:
            return "CG_STORE_PW_MODIFY";
        case CG_STORE_CLOSE:
            return "CG_STORE_CLOSE";
        case CG_STORE_ITEM_IN:
            return "CG_STORE_ITEM_IN";
        case CG_STORE_ITEM_OUT:
            return "CG_STORE_ITEM_OUT";
        case CG_STORE_MONEY_IN:
            return "CG_STORE_MONEY_IN";
        case CG_STORE_MONEY_OUT:
            return "CG_STORE_MONEY_OUT";
        case CG_ITEM_MOVE_SUCC:
            return "CG_ITEM_MOVE_SUCC";
        case GC_ITEM_MOVE_FAIL:
            return "GC_ITEM_MOVE_FAIL";
        case GC_CHAR_MOVE:
            return "GC_CHAR_MOVE";
        case GC_CHAR_DATA_LOAD:
            return "GC_CHAR_DATA_LOAD";
        case GC_ENTER_FAIL:
            return "GC_ENTER_FAIL";
        case GC_ITEM_MAP_REMOVE:
            return "GC_ITEM_MAP_REMOVE";
        case GC_ITEM_PICKUP_SUCC:
            return "GC_ITEM_PICKUP_SUCC";
        case GC_ITEM_DROP_SUCC:
            return "GC_ITEM_DROP_SUCC";
        case GC_INVENTORY_ITEM_LIST:
            return "GC_INVENTORY_ITEM_LIST";
        case GC_CRT_LOAD:
            return "GC_CRT_LOAD";
        case GC_CHAR_EXIT_SUCC:
            return "GC_CHAR_EXIT_SUCC";
        case GC_QUEST_SUCC:
            return "GC_QUEST_SUCC";
        case GC_VIEW_REMOVE_ALL:
            return "GC_VIEW_REMOVE_ALL";
        case GC_TRADE_BUY_SUCC:
            return "GC_TRADE_BUY_SUCC";
        case GC_TRADE_SELL_SUCC:
            return "GC_TRADE_SELL_SUCC";
        case GC_TRADE_BUY_FAIL:
            return "GC_TRADE_BUY_FAIL";
        case GC_TRADE_SELL_FAIL:
            return "GC_TRADE_SELL_FAIL";
        case GC_LEVEL_UP_SUCC:
            return "GC_LEVEL_UP_SUCC";
        case GC_LEVEL_UP_FAIL:
            return "GC_LEVEL_UP_FAIL";
        case GC_CHAR_STATUS_UP_SUCC:
            return "GC_CHAR_STATUS_UP_SUCC";
        case GC_CHAR_STATUS_UP_FAIL:
            return "GC_CHAR_STATUS_UP_FAIL";
        case GC_CHAR_SKILL_UP_EX_SUCC:
            return "GC_CHAR_SKILL_UP_EX_SUCC";
        case GC_CHAR_SKILL_UP_EX_FAIL:
            return "GC_CHAR_SKILL_UP_EX_FAIL";
        case GC_ITEM_CONFIRM_NPC_SUCC:
            return "GC_ITEM_CONFIRM_NPC_SUCC";
        case GC_ITEM_CONFIRM_NPC_FAIL:
            return "GC_ITEM_CONFIRM_NPC_FAIL";
        case GC_STORE_OPEN_SUCC:
            return "GC_STORE_OPEN_SUCC";
        case GC_STORE_OPEN_FAIL:
            return "GC_STORE_OPEN_FAIL";
        case GC_STORE_PW_MODIFY_SUCC:
            return "GC_STORE_PW_MODIFY_SUCC";
        case GC_STORE_PW_MODIFY_FAIL:
            return "GC_STORE_PW_MODIFY_FAIL";
        case GC_STORE_CLOSE_SUCC:
            return "GC_STORE_CLOSE_SUCC";
        case GC_STORE_ITEM_IN:
            return "GC_STORE_ITEM_IN";
        case GC_STORE_ITEM_OUT:
            return "GC_STORE_ITEM_OUT";
        case GC_STORE_MONEY_IN_SUCC:
            return "GC_STORE_MONEY_IN_SUCC";
        case GC_STORE_MONEY_OUT_SUCC:
            return "GC_STORE_MONEY_OUT_SUCC";
        case GC_STORE_MONEY_FAIL:
            return "GC_STORE_MONEY_FAIL";
        default:
            return "UNKNOWN";
        }
    }
}
