ALTER TABLE character ADD COLUMN hp INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE character ADD COLUMN ap INTEGER NOT NULL DEFAULT 500;
ALTER TABLE character ADD COLUMN fame INTEGER NOT NULL DEFAULT 2556;
